/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SistemaGestionRouteImport } from './routes/sistema-gestion'
import { Route as PropositoRouteImport } from './routes/proposito'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as NovedadesRouteImport } from './routes/novedades'
import { Route as LugarRouteImport } from './routes/lugar'
import { Route as EspecialidadesRouteImport } from './routes/especialidades'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as DerivantesRouteImport } from './routes/derivantes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CoberturasRouteImport } from './routes/coberturas'
import { Route as IndexRouteImport } from './routes/index'

const SistemaGestionRoute = SistemaGestionRouteImport.update({
  id: '/sistema-gestion',
  path: '/sistema-gestion',
  getParentRoute: () => rootRouteImport,
} as any)
const PropositoRoute = PropositoRouteImport.update({
  id: '/proposito',
  path: '/proposito',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const NovedadesRoute = NovedadesRouteImport.update({
  id: '/novedades',
  path: '/novedades',
  getParentRoute: () => rootRouteImport,
} as any)
const LugarRoute = LugarRouteImport.update({
  id: '/lugar',
  path: '/lugar',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialidadesRoute = EspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const DerivantesRoute = DerivantesRouteImport.update({
  id: '/derivantes',
  path: '/derivantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturasRoute = CoberturasRouteImport.update({
  id: '/coberturas',
  path: '/coberturas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coberturas': typeof CoberturasRoute
  '/contacto': typeof ContactoRoute
  '/derivantes': typeof DerivantesRoute
  '/equipo': typeof EquipoRoute
  '/especialidades': typeof EspecialidadesRoute
  '/lugar': typeof LugarRoute
  '/novedades': typeof NovedadesRoute
  '/pacientes': typeof PacientesRoute
  '/proposito': typeof PropositoRoute
  '/sistema-gestion': typeof SistemaGestionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coberturas': typeof CoberturasRoute
  '/contacto': typeof ContactoRoute
  '/derivantes': typeof DerivantesRoute
  '/equipo': typeof EquipoRoute
  '/especialidades': typeof EspecialidadesRoute
  '/lugar': typeof LugarRoute
  '/novedades': typeof NovedadesRoute
  '/pacientes': typeof PacientesRoute
  '/proposito': typeof PropositoRoute
  '/sistema-gestion': typeof SistemaGestionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coberturas': typeof CoberturasRoute
  '/contacto': typeof ContactoRoute
  '/derivantes': typeof DerivantesRoute
  '/equipo': typeof EquipoRoute
  '/especialidades': typeof EspecialidadesRoute
  '/lugar': typeof LugarRoute
  '/novedades': typeof NovedadesRoute
  '/pacientes': typeof PacientesRoute
  '/proposito': typeof PropositoRoute
  '/sistema-gestion': typeof SistemaGestionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coberturas'
    | '/contacto'
    | '/derivantes'
    | '/equipo'
    | '/especialidades'
    | '/lugar'
    | '/novedades'
    | '/pacientes'
    | '/proposito'
    | '/sistema-gestion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coberturas'
    | '/contacto'
    | '/derivantes'
    | '/equipo'
    | '/especialidades'
    | '/lugar'
    | '/novedades'
    | '/pacientes'
    | '/proposito'
    | '/sistema-gestion'
  id:
    | '__root__'
    | '/'
    | '/coberturas'
    | '/contacto'
    | '/derivantes'
    | '/equipo'
    | '/especialidades'
    | '/lugar'
    | '/novedades'
    | '/pacientes'
    | '/proposito'
    | '/sistema-gestion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoberturasRoute: typeof CoberturasRoute
  ContactoRoute: typeof ContactoRoute
  DerivantesRoute: typeof DerivantesRoute
  EquipoRoute: typeof EquipoRoute
  EspecialidadesRoute: typeof EspecialidadesRoute
  LugarRoute: typeof LugarRoute
  NovedadesRoute: typeof NovedadesRoute
  PacientesRoute: typeof PacientesRoute
  PropositoRoute: typeof PropositoRoute
  SistemaGestionRoute: typeof SistemaGestionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sistema-gestion': {
      id: '/sistema-gestion'
      path: '/sistema-gestion'
      fullPath: '/sistema-gestion'
      preLoaderRoute: typeof SistemaGestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposito': {
      id: '/proposito'
      path: '/proposito'
      fullPath: '/proposito'
      preLoaderRoute: typeof PropositoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novedades': {
      id: '/novedades'
      path: '/novedades'
      fullPath: '/novedades'
      preLoaderRoute: typeof NovedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lugar': {
      id: '/lugar'
      path: '/lugar'
      fullPath: '/lugar'
      preLoaderRoute: typeof LugarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialidades': {
      id: '/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof EspecialidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/derivantes': {
      id: '/derivantes'
      path: '/derivantes'
      fullPath: '/derivantes'
      preLoaderRoute: typeof DerivantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coberturas': {
      id: '/coberturas'
      path: '/coberturas'
      fullPath: '/coberturas'
      preLoaderRoute: typeof CoberturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoberturasRoute: CoberturasRoute,
  ContactoRoute: ContactoRoute,
  DerivantesRoute: DerivantesRoute,
  EquipoRoute: EquipoRoute,
  EspecialidadesRoute: EspecialidadesRoute,
  LugarRoute: LugarRoute,
  NovedadesRoute: NovedadesRoute,
  PacientesRoute: PacientesRoute,
  PropositoRoute: PropositoRoute,
  SistemaGestionRoute: SistemaGestionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
